name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: filter-govt-bills
  ECR_REGISTRY: 125839941772.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Push Docker image to Amazon ECR
        id: push-image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
