name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECR_REPOSITORY: filter-govt-bills
  AWS_ECR_REGISTRY: 125839941772.dkr.ecr.eu-west-1.amazonaws.com
  AWS_ECR_IMAGE_TAG: latest
  AWS_ECS_CLUSTER_NAME: filter-govt-bills
  AWS_ECS_SERVICE_NAME: filter-govt-bills

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - uses: docker/setup-buildx-action@v1
      
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$AWS_ECR_IMAGE_TAG

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Create ECS task definition
        id: register-task-definition
        run: |
          TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://task-definition.json | jq -r .taskDefinition.taskDefinitionArn)
          echo "task-definition-arn=$TASK_DEFINITION_ARN" >> $GITHUB_OUTPUT

      - name: Update ECS service
        run: |
          TASK_DEFINITION_ARN=${{ steps.register-task-definition.outputs.task-definition-arn }}
          aws ecs update-service --cluster $AWS_ECS_CLUSTER_NAME --service $AWS_ECS_SERVICE_NAME --task-definition $TASK_DEFINITION_ARN
